
export const projects = [
    {
        name: "Inbound vs. Outbound Marketing",
        category: "writing, marketing",
        company: "HIVE Digital Strategy",
        type: "Blog Article",
        description: "An educational blog post written for HIVE Digital Strategy, looking at the differences between outbound and inbound marketing techniques.",
        link: "https://blog.hivedigitalstrategy.com/inbound-vs.-outbound-marketing-why-your-business-benefits-with-inbound",
    },
    {
        name: "Drop Website Theme",
        category: "development, marketing",
        company: "HIVE Digital Strategy",
        type: "Web Development",
        description: "A colorful and concise website theme developed on the HubSpot CMS. Owner of design and development.",
        link: "https://marketplace.hubspot.com/products/hivedigitalstrategy/drop-theme",
    },
    {
        name: "The YardBuster Story",
        category: "writing, marketing",
        company: "Cultivate",
        type: "Blog Article",
        description: "An informational and promotional blog post written for Cultivate. ",
        link: "https://cultivate.ngo/blog/the-yardbuster-story",
    },
    {
        name: "Saving the Oceans With RBX",
        category: "writing, marketing", 
        company: "RBX",
        type: "Blog Article",
        description: "Written to promote an Earth Day promotional sale, this blog post includes methods for living more sustainably.",
        link: "https://www.rbxactive.com/blogs/feelin-it/help-save-our-oceans-with-rbx",
    },
    {
        name: "Hello Dottie",
        category: "writing",
        company: "Cultivate",
        type: "Long-form Article",
        description: "It's the gift of the old to share their stories with the young. While working for a non-profit providing safety net services for older adults, I had the opportunity to share my grandmother's story.",
        link: "https://cultivate.ngo/blog/hello-dottie",
    },
    {
        name: "Say Hello to Sister Carmen",
        category: "writing, marketing",
        company: "Cultivate",
        type: "Promotional Blog",
        description: "A feature written for a non-profit partner of Cultivate.",
        link: "https://cultivate.ngo/blog/say-hello-to-sister-carmen",
    },
    {
        name: "Take a Hike",
        category: "writing, print",
        company: "Colorado Traveler Magazine",
        type: "Print Article",
        description: "A travel article written for Colorado Traveler Magazine covering hikes across the Front Range of Colorado.",
        link: "https://files.journoportfolio.com/users/25459/uploads/4c60a6fc-8b5d-438e-b46e-5eb22d35ff44.pdf",
    },
    {
        name: "Two-Wheeling Around",
        category: "writing, print",
        company: "Colorado Traveler Magazine",
        type: "Print Ad-Editorial",
        description: "An editorial advertisement promoting rental bicycles in Denver, Colorado.",
        link: "https://files.journoportfolio.com/users/25459/uploads/44b038b5-c268-4f9a-a7e5-2e53a920a0a4.pdf",
    },
    {
        name: "Task Tracker",
        category: "development",
        type: "Personal Project",
        description: "A task tracking app designed to mimic the functionality of a popular project managment app like Trello.",
        link: "https://mello-melanie-locke.herokuapp.com/boards",
    },
    {
        name: "Digital To-Do List",
        category: "development",
        type: "Personal Project",
        description: "A digital to-do list where tasks can be added and crossed off.",
        link: "https://todo-melanie-locke.herokuapp.com/",
    },
];
